### ISSUE TITLE
`julia test/runtests.jl` fails

### ISSUE THREAD

**Issue by bicycle1885** [BioJulia/Bio.jl#174]
The following CLI testing fails, I guess, since #161:

```
~/.j/v/Bio (master|…) $ julia test/runtests.jl
ERROR: LoadError: SystemError: unable to read directory util: No such file or directory
 in readdir at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in anonymous at no file
 in include at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in process_options at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in _start at /usr/local/julia/v0.4/lib/julia/sys.dylib
while loading /Users/kenta/.julia/v0.4/Bio/test/runtests.jl, in expression starting on line 25
~/.j/v/Bio (master|…) $ julia test/runtests.jl seq
ERROR: LoadError: SystemError: unable to read directory util: No such file or directory
 in readdir at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in anonymous at no file
 in include at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in process_options at /usr/local/julia/v0.4/lib/julia/sys.dylib
 in _start at /usr/local/julia/v0.4/lib/julia/sys.dylib
while loading /Users/kenta/.julia/v0.4/Bio/test/runtests.jl, in expression starting on line 25
```

CC: @Ward9250

**Comment by Ward9250** [comment]
Fixed by #176. Thanks @bicycle1885 :+1:

**Comment by bicycle1885** [comment]
This is not yet fixed. Try `julia test/runtests.jl` on your machine.

**Comment by Ward9250** [comment]
@bicycle1885 Ah! Sorry I think I see the issue, I got distracted by someone at work and forgot to edit the last file that needed change to fix this. It should be ok now, but I'll wait to close until you've tried :+1:

**Comment by bicycle1885** [comment]
💯
